---
galaxy_info:
  role_name: fzf
  description: Install fzf, a command-line fuzzy finder
  author: donhector
  company: darkenv.com

  license: MIT

  min_ansible_version: 2.11

  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - fzf
    - ubuntu
    - debian

dependencies: []
