---
# tasks file for common

- name: Install common packages
  become: true
  ansible.builtin.apt:
    name: "{{ common_packages }}"
    state: present
    update_cache: true
    cache_valid_time: 600
  retries: 3
  register: result
  until: result is succeeded
