---
galaxy_info:
  role_name: ripgrep
  description: ripgrep recursively searches directories for a regex pattern while respecting your gitignore
  author: donhector
  company: darkenv.com

  license: MIT

  min_ansible_version: 2.11

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - ripgrep
    - ubuntu
    - debian

dependencies: []
