---
galaxy_info:
  role_name: python
  description: Setup python including pip
  author: donhector
  company: darkenv.com

  license: MIT

  min_ansible_version: 2.11

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - python
    - ubuntu
    - debian

dependencies: []
