---
- name: Converge
  hosts: all
  roles:
    # - role: common
    # - role: apt_proxy
    # - role: asdf
    # - role: awscli
    # - role: bat
    # - role: fd
    # - role: fonts
    # - role: fzf
    # - role: gh
    # - role: hugo
    - role: ../../roles/jq
    # - role: python
    # - role: ripgrep
    # - role: yq
    # - role: podman
    # - role: docker
    - role: ../../roles/sudoers

  # collections: donhector.workstation
