---
# tasks file for hugo

- name: Check if Hugo {{ hugo_version }} is installed
  ansible.builtin.shell: hugo version || true
  register: hugo_check
  changed_when: false


- name: Install Hugo {{ hugo_version }}
  become: true
  ansible.builtin.unarchive:
    remote_src: true
    src: "{{ hugo_dl_url }}"
    dest: "{{ hugo_path | dirname }}"
    extra_opts:
      - hugo  # Extract just the binry file (e.g. 'tar -x -f file.tgz hugo')
    mode: 0755
  when: >
    hugo_check.stdout_lines | length == 0
    or hugo_version not in hugo_check.stdout_lines[0]


## TODO: autocompletion
