---
# tasks file for jq

- name: Check if jq {{ jq_version }} is present
  shell: jq --version || true
  register: jq_check
  changed_when: false

- name: Setup jq {{ jq_version }}
  become: true
  when: >
    jq_check.stdout_lines | length == 0
    or jq_version not in jq_check.stdout
  block:
    - name: Install jq {{ jq_version }}
      get_url:
        url: "{{ jq_dl_url }}"
        dest: "{{ jq_path }}"
        force: true
        owner: root
        group: root
        mode: 0755

    - name: Create man page directory
      file:
        path: "{{ jq_man_path | dirname }}"
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Install man page
      get_url:
        url: "{{ jq_man_dl_url }}"
        dest: "{{ jq_man_path }}"
        force: true
        owner: root
        group: root
