---
# tasks file for yq

- name: Check if yq {{ yq_version }} is installed
  ansible.builtin.shell: yq --version || true
  register: yq_check
  changed_when: false

- name: Install yq
  become: true
  ansible.builtin.get_url:
    url: "{{ yq_dl_url }}"
    dest: "{{ yq_path }}"
    force: true
    owner: root
    group: root
    mode: 0755
  when: >
    yq_check.stdout_lines | length == 0
    or yq_version not in yq_check.stdout_lines[0]

## TODO completions
## see https://mikefarah.gitbook.io/yq/commands/shell-completion
