---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update apt cache.
      become: true
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'

  roles:
    - role: donhector.fonts
