---
galaxy_info:
  role_name: bat
  description: Install bat, a cat(1) clone with wings.
  author: donhector
  company: darkenv.com

  license: MIT

  min_ansible_version: 2.11

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - bat
    - ubuntu
    - debian

dependencies: []
