---
galaxy_info:
  author: donhector
  description: font installation
  company: darkenv.com
  role_name: fonts

  license: MIT

  min_ansible_version: 2.11

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - fonts
    - ubuntu
    - debian

dependencies: []
