---
galaxy_info:
  role_name: docker
  description: Install docker
  author: donhector
  company: darkenv.com

  license: MIT

  min_ansible_version: 2.11

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - docker
    - ubuntu
    - debian

dependencies: []
