---
# tasks file for python

- name: Include system tasks
  ansible.builtin.include_tasks: system.yml


- name: Include pip tasks
  ansible.builtin.include_tasks: pip.yml


- name: Include pipx tasks
  ansible.builtin.include_tasks: pipx.yml


- name: Include poetry tasks
  ansible.builtin.include_tasks: poetry.yml
