---
galaxy_info:
  role_name: fd
  description: Install fd, a simple, fast and user-friendly alternative to 'find'
  author: donhector
  company: darkenv.com

  license: MIT

  min_ansible_version: 2.11

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - fd
    - ubuntu
    - debian

dependencies: []
