---
galaxy_info:
  role_name: podman
  description: Install podman and friends from Kubic repo
  author: donhector
  company: darkenv.com

  license: MIT

  min_ansible_version: 2.11

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - podman
    - ubuntu
    - debian

dependencies: []
