---
galaxy_info:
  role_name: hugo
  description: The world's fastest framework for building websites.
  author: donhector
  company: darkenv.com

  license: MIT

  min_ansible_version: 2.11

  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - hugo
    - ubuntu
    - debian

dependencies: []
