---
galaxy_info:
  role_name: terraform
  description: Install Terraform from Hashicorp
  author: donhector
  company: darkenv.com

  license: MIT

  min_ansible_version: 2.11

  platforms:
    - name: EL
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - terraform
    - ubuntu
    - debian

dependencies: []
