---
galaxy_info:
  role_name: jq
  description: Install jq, the command-line JSON processor
  author: donhector
  company: darkenv.com

  license: MIT

  min_ansible_version: 2.11

  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - jq
    - ubuntu
    - debian

dependencies: []
