---
galaxy_info:
  role_name: awscli
  description: Install aws-cli via url
  author: donhector
  company: darkenv.com

  license: MIT

  min_ansible_version: 2.11

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - aws
    - awscli
    - ubuntu
    - debian

dependencies: []
